image: java:8-jdk

stages:
  - build
  #- test
  - deploy

before_script:
  - docker info
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
    - cp build/libs/*.jar /home/ubuntu/deploy/cast-server
  artifacts:
    paths:
      - build/libs/ #*.jar
    #expire_in: 1 week
  #only:
  #    - master

deploy:
  stage: deploy
  script:
    - cd /home/ubuntu/deploy/
    - pwd
    - /home/ubuntu/deploy/deploy.sh
    #docker build -f /home/ubuntu/deploy/Dockerfile-be -t aliaspace/cast:be-4.0.0 .
    #/home/ubuntu/deploy/deploy.sh

    #test:
    #    stage: test
    #    script:
    #      - ./gradlew check

after_script:
  - echo "End CI"
