#ok
#image: gradle:jdk8

#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

#before_script:
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - chmod +x ./gradlew

#stages:
#  - build
#  - test

#build:
#  stage: build
#  script: ./gradlew --build-cache assemble
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle


image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

#non funge ancora
#deploy:
#  stage: deploy
#  script:
#    - ./gradlew deploy

after_script:
  - echo "End CI"
